spring.application.name=bpo
server.port=8080

# =====================
# BANCO LOCAL
# =====================
spring.datasource.url=jdbc:mysql://localhost:3306/hds_bpo?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=hubhds@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================
# JPA / HIBERNATE
# =====================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.sql.descriptor.binding=TRACE

# =====================
# FRONT-END
# =====================
app.front-url=https://hubhds.com.br/assessor/esqueceu

# =====================
# EMAIL LOCAL
# =====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vitorpj1602@gmail.com
spring.mail.password=gwliqucxacxkzbsh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =====================
# JWT
# =====================
api.security.token.secret=99EK3sLCMGCkORAJMNdgzSTtyFOu7jsHLcEJmqw+LNq9rHGQpFKrqz/iks+ulOqLtvyqCSNJ1Dqeix1vfiqcOQ==

# =====================
# MERCADO PAGO LOCAL / TESTE
# =====================
mercadopago.base-url=https://api.mercadopago.com
mercadopago.access-token=APP_USR-3907944917613997-032707-076a3f5620c35f56f082a88d1ec2b631-3297088104
mercadopago.webhook-secret=550d4881bde1391269cd6b26008e1e9f22b475a928f1a7cd3618c43f5ec4250c
mercadopago.back-url=https://unintoxicating-charmain-unfraudulently.ngrok-free.dev/webhooks/retorno

mercadopago.subscription-reason=Assessor BPO
mercadopago.subscription-monthly-amount=29.90
mercadopago.subscription-yearly-amount=299.90
mercadopago.currency-id=BRL

mercadopago.mock=false
mercadopago.mock-user-id=1


# =====================
# CONFIGURAÇÕES RENDER - DEIXAR COMENTADO POR ENQUANTO
# =====================

#server.port=${PORT:8080}

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
#spring.jpa.show-sql=${JPA_SHOW_SQL:false}
#spring.jpa.properties.hibernate.format_sql=false
#logging.level.org.hibernate.orm.sql.descriptor.binding=OFF

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#api.security.token.secret=${JWT_SECRET}

#mercadopago.base-url=https://api.mercadopago.com
#mercadopago.access-token=${MERCADO_PAGO_ACCESS_TOKEN}
#mercadopago.webhook-secret=${MERCADO_PAGO_WEBHOOK_SECRET}
#mercadopago.back-url=${MERCADO_PAGO_BACK_URL}